"""Curated seed list of well-known AI tools (guaranteed quality baseline)."""
from src.discovery.base import BaseSource, Candidate

SEEDS = [
    ("ChatGPT", "https://chat.openai.com", "AI conversational assistant by OpenAI", "Chat & Assistant"),
    ("Cursor", "https://cursor.com", "AI-first code editor with natural language code editing", "Coding"),
    ("Midjourney", "https://www.midjourney.com", "Text-to-image generation service", "Image Generation"),
    ("Runway", "https://runwayml.com", "AI video generation and editing platform", "Video Generation"),
    ("ElevenLabs", "https://elevenlabs.io", "AI voice generation and speech synthesis", "Audio & Music"),
    ("Perplexity", "https://www.perplexity.ai", "AI-powered answer engine with cited sources", "Search"),
    ("Hugging Face", "https://huggingface.co", "Platform hosting open ML models and datasets", "Developer Tools"),
    ("GitHub Copilot", "https://github.com/features/copilot", "AI pair programmer inside the editor", "Coding"),
    ("Notion AI", "https://www.notion.so/product/ai", "AI writing and summarization inside Notion", "Writing"),
    ("Jasper", "https://www.jasper.ai", "AI content platform for marketing copy", "Marketing"),
    ("Canva Magic Studio", "https://www.canva.com/magic-studio", "AI design tools inside Canva", "Design"),
    ("Zapier AI", "https://zapier.com/ai", "AI-powered workflow automation", "Automation"),
    ("Synthesia", "https://www.synthesia.io", "AI video generation with avatars", "Video Generation"),
    ("DeepL", "https://www.deepl.com", "Neural machine translation service", "Translation"),
    ("Otter.ai", "https://otter.ai", "AI meeting transcription and notes", "Speech Recognition"),
    ("Stability AI", "https://stability.ai", "Open-source generative image models (Stable Diffusion)", "Image Generation"),
    ("Anthropic Claude", "https://claude.ai", "Constitutional AI assistant by Anthropic", "Chat & Assistant"),
    ("Google Gemini", "https://gemini.google.com", "Multimodal AI assistant by Google", "Chat & Assistant"),
    ("LangChain", "https://www.langchain.com", "Framework for building LLM applications", "Agent Framework"),
    ("CrewAI", "https://www.crewai.com", "Multi-agent orchestration framework", "Agent Framework"),
    ("Ollama", "https://ollama.com", "Run large language models locally", "Developer Tools"),
    ("Windsurf", "https://codeium.com/windsurf", "AI coding agent IDE by Codeium", "Coding"),
    ("Gamma", "https://gamma.app", "AI presentation and document generator", "Design"),
    ("Copy.ai", "https://www.copy.ai", "AI copywriting for go-to-market teams", "Marketing"),
    ("Elicit", "https://elicit.com", "AI research assistant for academic papers", "Research"),
    ("Poe", "https://poe.com", "Multi-model AI chat aggregator by Quora", "Chat & Assistant"),
    ("Character.AI", "https://character.ai", "Conversational AI characters platform", "Chat & Assistant"),
    ("Leonardo.Ai", "https://leonardo.ai", "AI art and asset generation for creators", "Image Generation"),
    ("Ideogram", "https://ideogram.ai", "Text-to-image generation with accurate text rendering", "Image Generation"),
    ("Suno", "https://suno.com", "AI music generation from text prompts", "Audio & Music"),
    ("Udio", "https://www.udio.com", "AI music creation platform", "Audio & Music"),
    ("HeyGen", "https://www.heygen.com", "AI avatar video generation", "Video Generation"),
    ("Descript", "https://www.descript.com", "AI-powered video and podcast editing", "Audio & Music"),
    ("Fireflies.ai", "https://fireflies.ai", "AI meeting assistant and transcription", "Speech Recognition"),
    ("Fathom", "https://fathom.video", "Free AI meeting notetaker", "Speech Recognition"),
    ("Grammarly", "https://www.grammarly.com", "AI writing assistant and grammar checker", "Writing"),
    ("QuillBot", "https://quillbot.com", "AI paraphrasing and writing tool", "Writing"),
    ("Claude Code", "https://claude.com/product/claude-code", "Agentic coding tool by Anthropic", "Coding"),
    ("Replit", "https://replit.com", "AI-powered cloud IDE with agent", "Coding"),
    ("v0", "https://v0.dev", "AI UI generation by Vercel", "Design"),
    ("Figma AI", "https://www.figma.com", "AI features in collaborative design tool", "Design"),
    ("Beautiful.ai", "https://www.beautiful.ai", "AI presentation maker", "Design"),
    ("Surfer SEO", "https://surferseo.com", "AI-powered SEO content optimization", "Marketing"),
    ("HubSpot AI", "https://www.hubspot.com", "AI features across CRM platform", "Marketing"),
    ("Julius AI", "https://julius.ai", "AI data analyst for charts and analysis", "Data & Analytics"),
    ("Hex", "https://hex.tech", "Collaborative data workspace with AI", "Data & Analytics"),
    ("Lovable", "https://lovable.dev", "AI full-stack app builder", "Developer Tools"),
    ("Bolt.new", "https://bolt.new", "AI web app development in the browser", "Developer Tools"),
    ("AutoGen", "https://microsoft.github.io/autogen", "Microsoft multi-agent framework", "Agent Framework"),
    ("DeepSeek", "https://www.deepseek.com", "Open AI models and chat assistant", "Chat & Assistant"),
    ("Mistral AI", "https://mistral.ai", "Frontier open-weights generative AI models", "Chat & Assistant"),
    ("Groq", "https://groq.com", "Ultra-fast LPU inference engine for AI models", "Developer Tools"),
    ("Cohere", "https://cohere.com", "Enterprise AI platform for search, discovery, and generation", "Developer Tools"),
    ("OpenRouter", "https://openrouter.ai", "Unified API interface for LLMs and AI models", "Developer Tools"),
    ("Together AI", "https://www.together.ai", "Cloud platform for training and fine-tuning open source AI", "Developer Tools"),
    ("Krea AI", "https://www.krea.ai", "Real-time AI image generation and enhancement studio", "Image Generation"),
    ("Luma Dream Machine", "https://lumalabs.ai/dream-machine", "High-quality realistic video generation from video models", "Video Generation"),
    ("Pika", "https://pika.art", "Idea-to-video platform with creative effects", "Video Generation"),
    ("Phind", "https://www.phind.com", "AI search engine and pair programmer for developers", "Search"),
    ("Chroma", "https://www.trychroma.com", "Open-source AI-native embedding database", "Data & Analytics"),
    ("Pinecone", "https://www.pinecone.io", "Serverless vector database for vector search applications", "Data & Analytics"),
    ("Qdrant", "https://qdrant.tech", "Open-source vector similarity search engine", "Data & Analytics"),
    ("ComfyUI", "https://www.comfy.org", "Node-based graphical interface for Stable Diffusion and FLUX", "Image Generation"),
    ("Aider", "https://aider.chat", "AI pair programming terminal agent", "Coding"),
    ("Continue", "https://www.continue.dev", "Open-source AI code assistant for VS Code and JetBrains", "Coding"),
    ("Weights & Biases", "https://wandb.ai", "AI developer platform for tracking and evaluation", "Developer Tools"),
]


class SeedSource(BaseSource):
    name = "seed"

    def discover(self) -> list:
        return [Candidate(name=n, url=u, description=d, category_hint=c,
                           source_name="Curated Seed", source_url=u)
                for n, u, d, c in SEEDS]
